#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Nov 26 11:46:41 CET 2021
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_mult_behav -key {Behavioral:mult_tb:Functional:tb_mult} -tclbatch tb_mult.tcl -view /home/putoale/Documenti/monmult_proj_v2/monmult_v2/Sources/Testbenches/tb_mult_behav.wcfg -log simulate.log"
xsim tb_mult_behav -key {Behavioral:mult_tb:Functional:tb_mult} -tclbatch tb_mult.tcl -view /home/putoale/Documenti/monmult_proj_v2/monmult_v2/Sources/Testbenches/tb_mult_behav.wcfg -log simulate.log

